env:
  browser: true
  es6: true
  node: true

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly

parser: "@typescript-eslint/parser"

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2020
  sourceType: module
  project: ./tsconfig.json

plugins:
  - "@typescript-eslint"
overrides:
  - files: "*.js"
    rules:
      "@typescript-eslint/no-var-requires": 0
