ci:
  collect:
    startServerCommand: yarn serve
    url: http://localhost:9000/c/
  assert:
    preset: lighthouse:recommended
    assertions:
      color-contrast: warn
      font-display: warn
      unminified-css: warn
      unused-css-rules: warn
      uses-rel-preconnect: warn
      uses-responsive-images: warn
      uses-http2: warn
      redirects-http: warn
      unused-javascript: warn
  upload:
    target: temporary-public-storage
