ci:
  collect:
    startServerCommand: yarn prod
    url: http://localhost:9000/c/
  assert:
    preset: lighthouse:recommended
    assertions:
      color-contrast: warn
      non-composited-animations: warn
      unminified-css: warn
      unused-css-rules: warn
      uses-responsive-images: warn
  upload:
    target: temporary-public-storage
