sudo: false
dist: trusty
language: node_js
cache: yarn
node_js:
  - stable
addons:
  chrome: stable
before_install:
  - yarn global add @lhci/cli
script:
  - yarn deploy
after_success:
  - lhci autorun
