- title: About Me
  content1: |
    I'm a senior of Undergraduate School of
    Electrical & Electronic Engineering in Faculty of Engineering,
    Kyoto University.
  content2: I study Computer Vision & Machine Learning.