- date: April 2016 - September 2020
  title: 京都大学
  content: 工学部 電気電子工学科
  link: https://www.s-ee.t.kyoto-u.ac.jp/
  color: success

- date: September 2016
  title: エレクトロニクスサマーキャンプ TA賞
  content: |
    京都大学工学部電気電子工学科主催のサマーキャンプ
    LEGO Mindstormsを使ったロボット製作
  link: https://www.s-ee.t.kyoto-u.ac.jp/ja/summercamp
  color: info

- date: September 2018
  title: エレクトロニクスサマーキャンプ 優勝
  content: |
    京都大学工学部電気電子工学科主催のサマーキャンプ
    倒立振子の自動制御コンテスト
  link: https://www.s-ee.t.kyoto-u.ac.jp/ja/summercamp/inv-pendulum/2018-kuee-sc3/report
  color: info

- date: March 2019 - December 2019
  title: ソフトウェアエンジニア (アルバイト)
  content: |
    C言語でのWindowsのカーネルモードデバイスドライバ開発
    C#言語でのWindowsのGUIアプリケーション開発
  link: null
  color: danger

- date: August 2019
  title: セキュリティ・キャンプ全国大会2019
  content: |
    独立行政法人情報処理推進機構によるセキュリティ・キャンプ事業のメインイベント
  link: https://www.ipa.go.jp/jinzai/camp/2019/zenkoku2019_index.html
  color: warning

- date: December 2019 -
  title: Webエンジニア (契約社員)
  content: |
    TypeScript, React, Vueでのフロントエンド開発
    チームビルディング，エンジニアリングマネジメント
  link: null
  color: danger

- date: January 2020 -
  title: CAMPHOR- コアメンバー
  content: 京都のIT系学生コミュニティCAMPHOR-の運営
  link: https://camph.net/
  color: success

- date: August 2020
  title: Cookpad Online Summer Internship 2020
  content: |
    Ruby on RailsによるWebアプリ開発
    サービス開発
  link: https://techlife.cookpad.com/entry/2020/09/16/100000
  color: danger

- date: September 2020
  title: VOYAGE GROUP GrowthTech
  content: |
    チーム開発
  link: https://voyagegroup.snar.jp/jobboard/detail.aspx?id=gOhDwyuFZ3o
  color: danger

- date: October 2020 -
  title: 奈良先端科学技術大学院大学
  content: |
    先端科学技術研究科 情報科学領域
    Interactive Media Design Labに在籍
  link: https://imdl.naist.jp/
  color: success
