- title: ARタテカン
  content: 絶対に撤去されないタテカン．京都新聞やNHK，様々なニュースサイトで紹介された．
  link: https://www.google.com/search?q=AR%E3%82%BF%E3%83%86%E3%82%AB%E3%83%B3
  img: ./images/products/artatekan.jpg
  tags:
    - Swift
    - ARKit2
  code: null

- title: AR折田先生像
  content: 絶対に撤去されない折田先生像．様々なニュースサイトで紹介された．
  link: https://twitter.com/5ebec/status/1099505242566094848?s=20
  img: ./images/products/arorita.jpg
  tags: 
    - Swift
    - ARKit2
  code: https://github.com/5ebec/AROritaSensei

- title: Ameyadar
  content: 各種SNSアカウント名に京都大学上空の予想降水量に応じた絵文字を貼付する．Twitterで運用中．
  link: https://twitter.com/5ebec
  img: ./images/products/ameyadar.jpg
  tags:
    - Python3
  code: https://github.com/5ebec/Ameyadar

- title: 単位取得率bot
  content: Twitter:@5ebec 宛に京大の講義名をツイートすると単位取得率を教えてくれる．
  link: https://twitter.com/5ebec
  img: ./images/products/tannishutoku.jpg
  tags:
    - Python3
  code: null

- title: AR名刺
  content: |
    QRコードがwebアプリのURL兼ARマーカーになっており，QRコードリーダで読み取ると名刺上に情報を表示することが出来る．
  link: https://arcard.5ebec.dev
  img: ./images/products/arcard.jpg
  tags:
    - AR.js
    - A-Frame
  code: https://github.com/5ebec/ARCard

