name: Lighthouse CI
on: pull_request

jobs:
  lighthouse-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install --frozen-lockfile --ignore-optional

      - name: Build
        run: yarn build

      - name: Run Lighthouse CI
        run: yarn lh
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
